name: MSBuild

on:
  push:
    branches: ["capy_main"]
  pull_request:
    branches: ["capy_main"]

env:
  SOLUTION_FILE_PATH: CapyComputer.slnx
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Verify Node
        run: node --version

      - name: Verify npm
        run: npm --version

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}
###beast is just a placeholder because I dont want to download the entire boost library
      - name: Install Boost via vcpkg
        run: |
          vcpkg install boost-beast:x64-windows
          vcpkg integrate install

      - name: Build
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /m /p:Configuration=${{ env.BUILD_CONFIGURATION }}
