name: MSBuild

on:
  push:
    branches: ["capy_main"]
  pull_request:
    branches: ["capy_main"]

env:
  SOLUTION_FILE_PATH: CapyOS-CONSOLE.slnx
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check the code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Install Boost via vcpkg
        run: |
          vcpkg install boost:x64-windows
          vcpkg integrate install

      - name: Build
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /m /p:Configuration=${{ env.BUILD_CONFIGURATION }}
